### ISSUE TITLE
sls deploy failed due to API SOCKET Hang up

### ISSUE THREAD

**Issue by karanrk** [serverless/serverless-openwhisk#156] opened 2019-02-06 19:00 UTC
Hello Team,

I did follow your documentation to set up serverless and ibm cloud functions credentials. I am able to deploy functions onto ibm cloud without sls, but when i tried deploying simple function using sls - it fails. Also note that sls deploy works just fine for aws lambda.

Below is error

ServerlessError: Failed to deploy function (my_service-dev-hello) due to error: Unknown Error From API: socket hang up

Stack Trace 

ServerlessError: Failed to deploy function (my_service-dev-hello) due to error: Unknown Error From API: socket hang up
    at ow.actions.create.then.catch.err (/home/faasdev/IBMcloud/node-js/my_service/node_modules/serverless-openwhisk/deploy/lib
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:111:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:98:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)

**Comment by jthomas** [comment] 2019-02-07 09:54
Hello @karanrk. 

What IBM Cloud region were you deploying to? Can you check the issue is still occuring? Sometimes there are intermittant network or platform issues.

**Comment by karanrk** [comment] 2019-02-07 19:48
Hi @jthomas

I was deploying to Dallas (api.ng.bluemix.net). Issue still persists and has been there for around 5 days now.Please let me know next steps.
Thanks!

**Comment by karanrk** [comment] 2019-02-07 20:19
Not sure if below information helps,
I am behind my company's proxy and When i tried deploying on GCP i get this error

Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1179:19)
    at Object.onceWrapper (events.js:285:13)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:439:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:111:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:98:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)

**Comment by jthomas** [comment] 2019-02-08 09:57
Hmm is your companies proxy blocking traffic? 

Can you access IBM Cloud Functions using the IBM Cloud CLI? If you run `ibmcloud wsk action list` what happen?

**Comment by karanrk** [comment] 2019-02-08 18:25
IBM Cloud CLI works fine, `ibmcloud wsk action list` returns  all the actions that i have created. I wonder how serverless works with Lambda and doesn't complain at all.

**Comment by jthomas** [comment] 2019-02-11 17:49
Hmm I'm struggling to think of a reason for this I'm afraid... 

Could you try deploying to a different IBM Cloud region?

**Comment by karanrk** [comment] 2019-02-11 18:54
Even though i have set proxy, but somehow the plugin seems to ignore the
proxy settings. After taking a stab at the TCP dump to check the network
traffic looks like plugin is unable to reach my proxy. Could you please let
me know how do i make this proxy available to plugin.

Best Regards,
Karan

**Comment by jthomas** [comment] 2019-02-12 11:33
Looking at other [tickets](https://github.com/serverless/serverless/issues/3256) referenced from this issue, it looks like AWS does have support for proxies
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L139-L148

This hasn't yet been implemented in the OpenWhisk plugin. If you would like to have a go at implementing this feature, we'd happily accept a PR?

**Comment by karanrk** [comment] 2019-02-13 23:49
Could you please point me to openwhisk sdk documentation ?

**Comment by jthomas** [comment] 2019-02-14 10:47
https://github.com/apache/incubator-openwhisk-client-js is the JS SDK used to interact with the OpenWhisk platform API.

**Comment by jthomas** [comment] 2019-07-05 07:49
I'm closing this issue as the downstream client library now supports proxies and can be used with the framework.

**Closed by jthomas** 2019-07-05 07:49 UTC
